title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://soma00333.github.io
baseurl: /profile

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
