title: Soma Utsumi
description: Profile for Soma Utsumi
theme: just-the-docs
color_scheme: dark

url: https://soma00333.github.io
baseurl: /profile

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
